---
apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    author: vamsi
    name: result-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
...